#! ruby
require 'test/unit'
require 'gtk3'
require 'gtk2clockapp/config'
require 'such/convention'

class TestConfig < Test::Unit::TestCase
  include Gtk2ClockApp
  def test_config
    # These keys map to non-standard `Pango` items...
    exception_keys = [:big_label,:medium_label,:small_label]
    exception_keys.all?{CONFIG[_1].is_a?Hash}
    exception = Such::Convention.validate(CONFIG)
    assert_equal exception_keys, exception.keys
  end
end

