#! ruby
require 'test/unit'
require 'gtk3'
require 'gtk2clockapp/config'

class TestConfig < Test::Unit::TestCase
  include Gtk2ClockApp

  def test_config
    # Checking convention use
    CONFIG.each do |k,v|
      msg = "#{k}: #{v.inspect}"
      case k
      when /^[A-Z_]+$/    # CAPS => Array of args
        assert_equal Array, v.class, msg
      when /^[a-z_]+$/    # lower => Hash of key to args
        assert_equal Hash, v.class, msg
      when /^[a-z_]+\!$/  # lower! => Array of keys
        assert_equal Array, v.class, msg
      when /^[a-zA-Z]+$/  # Camel => String|Numeric
        assert((v.class==String) || (v.kind_of? Numeric), msg)
      when /^[a-zA-Z]+!$/ # Camel! => Hash of key to configurable value
        assert_equal Hash, v.class, msg
      else
        raise "Got bad thing key :#{k}."
      end
    end
  end
end

